version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "4173:80" # Expose port 80 of the container to port 4173 of the host
    restart: always
    environment:
      NODE_ENV: production
