version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "4173:4173" # Expose port 4173
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
