export const pathNames = {
  HOME: "/",
  LOGIN: "/login",
  NOTIFICATION: "/notification",
  LETTER: "/letter",
  LETTER_CREATE: "/letter/create",
  ATTENDANCE: "/attendance",
  GRADE: "/grade",
  EXAM: "/exam",
  LOGOUT: "/logout",
  PROFILE: "/profile",
  JOIN_EXAM: "/exam/:id",
  ERROR: "/404",
  HISTORY_EXAM: "/exam/:id/history",
  CLASS: "/class",
};
